services:
#    ddl_ltree_extension.example:
#        class: DDL\LtreeExtensionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    ddl_ltreeextensionbundle.listener.ltreesubscriber:
        class: DDL\LtreeExtensionBundle\Listener\LtreeSubscriber
        arguments: [ "@ddl_ltreeextensionbundle.annotation.annotation_driver", "@property_accessor" ]
        tags:
            - { name: doctrine.event_subscriber }

    ddl_ltreeextensionbundle.annotation.annotation_driver:
        class: DDL\LtreeExtensionBundle\Annotation\Driver\AnnotationDriver
        arguments: [ "@annotation_reader" ]

    ddl_ltreeextensionbundle.treebuilder.treebuilderfromarrayresult:
        class: DDL\LtreeExtensionBundle\TreeBuilder\TreeBuilderFromArrayResult
        public: false

    ddl_ltreeextensionbundle.treebuilder.treebuilderfromobjectresult:
        class: DDL\LtreeExtensionBundle\TreeBuilder\TreeBuilderFromObjectResult
        arguments: [ "@property_accessor" ]
        public: false

    ddl_ltreeextensionbundle.treebuilder.treebuilder:
        class: DDL\LtreeExtensionBundle\TreeBuilder\TreeBuilder
        arguments: [ "@ddl_ltreeextensionbundle.treebuilder.treebuilderfromarrayresult", "@ddl_ltreeextensionbundle.treebuilder.treebuilderfromobjectresult" ]

    ddl_ltreeextensionbundle.repository_factory:
        class: DDL\LtreeExtensionBundle\Repository\RepositoryFactory
        arguments: [ "@ddl_ltreeextensionbundle.annotation.annotation_driver", "@property_accessor", "@ddl_ltreeextensionbundle.treebuilder.treebuilder" ]
