language: php
dist: bionic

php:
  - '7.3'
  - '7.4'

sudo: false

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --config phpunit.xml.dist
#
#jobs:
#  include:
#    - stage: Test
#      php: 7.2
#      env: DB=pgsql POSTGRESQL_VERSION=11.0
#      sudo: required
#      services:
#        - docker
#      before_script:
#        - bash ./tests/travis/install-postgres-11.sh
#    - stage: Test
#      php: 7.3
#      env: DB=pgsql POSTGRESQL_VERSION=11.0
#      sudo: required
#      services:
#        - docker
#      before_script:
#        - bash ./tests/travis/install-postgres-11.sh
#    - stage: Test
#      php: 7.4
#      env: DB=pgsql POSTGRESQL_VERSION=11.0 COVERAGE=yes
#      sudo: required
#      services:
#        - docker
#      before_script:
#        - bash ./tests/travis/install-postgres-11.sh
#
#  allow_failures:
#    - env: DEPENDENCIES=dev
#    - php: nightly